export const ACTIONS = {
  GET_CAR_LIST_LOADING: 'GET_CAR_LIST_LOADING',
  GET_CAR_LIST_SUCCESS: 'GET_CAR_LIST_SUCCESS',
  GET_CAR_LIST_ERROR: 'GET_CAR_LIST_ERROR',

  GET_CAR_DETAIL_LOADING: 'GET_CAR_DETAIL_LOADING',
  GET_CAR_DETAIL_SUCCESS: 'GET_CAR_DETAIL_SUCCESS',
};
